Improve vim-bundle performance and cleanup output
Increase performance of vim-bundle by running updates and installs in
parallel.  Add prompt to opt out of running vim-bundle.  Remove all
output produce by git.  Output error messages in red.  Output success
messages in green.

diff --git a/bin/vim-bundle b/bin/vim-bundle
--- a/bin/vim-bundle
+++ b/bin/vim-bundle
@@ -1,26 +1,57 @@
-#!/bin/sh
+#!/bin/bash
 # vim: set ft=sh sw=2 ts=2 expandtab:
+
+set -e
+
+read -n1 -p 'Would you like to update vim bundles? ' answer
+echo
+if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
+  echo "Skipping vim-bundle"
+  exit 0
+fi
+
+success() {
+  echo "$(tput setaf 2)${1}$(tput sgr0)"
+}
+error() {
+  echo "$(tput setaf 1)${1}$(tput sgr0)"
+}
+
+get_bundle() {
+  (
+    if [ -d "$2" ]; then
+      cd "${2}"
+      (
+        git fetch --all -q &>/dev/null
+        git rebase -q origin/HEAD &>/dev/null
+      )
+      if [ $? -eq 0 ]; then
+        success "${1}'s ${2} updated"
+      else
+        error "Error updating ${1}'s ${2}"
+      fi
+    else
+      ( git clone -q "git://github.com/${1}/${2}.git" &>/dev/null )
+      if [ $? -eq 0 ]; then
+        success "${1}'s ${2} installed"
+      else
+        error "Error installing ${1}'s ${2}"
+      fi
+    fi
+  )
+}
 
 [ -d "${HOME}/.vim/bundles" ] || mkdir -p "${HOME}/.vim/bundles"
 cd "${HOME}/.vim/bundles"
 
-get_bundle() {
-  (
-  if [ -d "$2" ]; then
-    echo "Updating $1's $2"
-    cd "$2"
-    git pull --rebase
-  else
-    git clone "git://github.com/$1/$2.git"
-  fi
-  )
-}
-
 # Read each ~/.vim/*.bundle file and install it
 for bundle in ${HOME}/.vim/*.bundle; do
   while read owner project; do
-    get_bundle $owner $project
+    get_bundle $owner $project &
   done < $bundle
+  wait
 done
 
 vim -c 'call pathogen#helptags()|q'
+
+exit 0
